services:
  - type: web
    name: admin-backend
    runtime: python3
    buildCommand: pip install -r server/requirements.txt
    startCommand: gunicorn --chdir server --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
